### ISSUE TITLE
BUG - SNDDATA.BIN, Container corrompendo.

### ISSUE THREAD

**Issue by zMath3ussMSF** [MiguelQueiroz010/SCEIVag-Pack#1]
Ao importar áudios de durações maior do que a do áudio original o container corrompe, onde o programa exibe um erro ao abri-lo e personagens na batalha ficam mudos ou nem sequer iniciam nela...

**Comment by MiguelQueiroz010** [comment]
Issue fixed by yourself on another account.
👌
